# Generated by Django 4.2.2 on 2023-06-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
